name: CI for main branch

on:
  push:
    branches: [main]

jobs:
  test-go:
    strategy:
      matrix:
        package-path:
          - '.'
          - receiver/cloudflaremetricsreceiver
          - receiver/runnreceiver
          - internal/tools
    uses: ./.github/workflows/wf-test-go.yml
    with:
      package-path: ${{ matrix.package-path }}
  
  lint-go:
    uses: ./.github/workflows/wf-lint-go.yml

  build:
    uses: ./.github/workflows/wf-build.yml
  
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: 364898
        private-key: ${{ secrets.ARTHUR1_BOT_PRIVATE_KEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
