name: CI for pull request

on:
  pull_request:

jobs:
  test-go:
    strategy:
      matrix:
        package-path:
          - '.'
          - receiver/cloudflaremetricsreceiver
          - receiver/runnreceiver
          - processor/mackerelattributesprocessor
          - internal/tools
      fail-fast: false
    uses: ./.github/workflows/wf-test-go.yml
    with:
      package-path: ${{ matrix.package-path }}
  
  lint-go:
    uses: ./.github/workflows/wf-lint-go.yml

  build:
    uses: ./.github/workflows/wf-build.yml
