name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache-dependency-path: "**/*.sum"
      - run: go install go.opentelemetry.io/collector/cmd/builder
        working-directory: ./internal/tools
      - run: builder --config ./otelcol-builder.yaml
