name: test-go

on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache-dependency-path: "**/*.sum"
      - run: go install github.com/mfridman/tparse
        working-directory: ./internal/tools
      - run: |
          set -o pipefail
          go test -json ./... | tparse -all -format markdown >> "$GITHUB_STEP_SUMMARY"
          cat "$GITHUB_STEP_SUMMARY"
        working-directory: ${{ inputs.package-path }}

  codegen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache-dependency-path: "**/*.sum"
      - run: go install go.opentelemetry.io/collector/cmd/mdatagen
        working-directory: ./internal/tools
      - run: |
          go generate ./...
          DIFF=$(git status --porcelain)
          if [ -n "$DIFF" ]; then
            echo "$DIFF"
            exit 1
          fi
        working-directory: ${{ inputs.package-path }}
